<div class="grid-1">
    <div class="title-grid"><span>estaca</span></div>
    <div class="content-gird">
            <div id="calendar"></div>
            
            <iframe src="https://www.google.com/calendar/embed?title=Calendario%3A%20Estaca&amp;height=600&amp;wkst=1&amp;bgcolor=%23cc9933&amp;src=s91ikb8oif63539lg739e9l3b8%40group.calendar.google.com&amp;color=%23875509&amp;ctz=America%2FSantiago" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>
            
        <div class="clear"> </div>
    </div>
</div>