<div class="grid-1">
    <div class="title-grid"><span>Multimedia - Videos</span></div>
    <div class="content-gird">
            <div id="calendar"></div>
            
            
            
            <p><a href="<?php echo $this->url(array('controller'=>'videos','action'=>'agregar'));?>">Agregar video</a></p>
            <table> 
            <tr> 
            <th>Nombre</th> 
            <th>Url</th>             
            <th>&nbsp;</th> 
            </tr> 
            <?php foreach($this->videos as $videos) : ?> 
            <tr> 
            <td><?php echo $this->escape($videos->nombre);?></td> 
            <td><?php echo $this->escape($videos->url);?></td> 
            <td> 
            <a href="<?php echo $this->url(array('controller'=>'videos','action'=>'editar','id'=>$videos->id));?>">Editar</a> 
            <a href="<?php echo $this->url(array('controller'=>'videos','action'=>'eliminar','id'=>$videos->id));?>">Borrar</a> 
            </td> 
            </tr> 
            <?php endforeach; ?> 
            </table>
            
            
        <div class="clear"> </div>
    </div>
</div>