<div class="centered">
           <ul id="main-nav"> 
                <li id="<?php echo $this->estado1 ?>"><a href="<?php echo $this->baseUrl() ?>/admin"><span>Portal</span></a></li> 

                <li><a href="<?php echo $this->baseUrl() ?>/admin"><span>Multimedia</span></a>
                    <ul>
                        <li><a href="<?php echo $this->baseUrl() ?>/admin/videos/index"><span>Videos</span></a></li>
                        <li><a href="<?php echo $this->baseUrl() ?>/admin/fotos/index"><span>Fotos</span></a></li>
                    </ul>
                </li>
                <li><a href="<?php echo $this->baseUrl() ?>/admin"><span>Reservas</span></a></li>
                <li><a href="<?php echo $this->baseUrl() ?>/admin"><span>Inventario</span></a></li>
                <li id="<?php echo $this->estado8; ?>"><a href="<?php echo $this->baseUrl() ?>/admin/clientes"><span>Lista de Clientes</span></a></li>
             </ul>
             
             <ul id="main-nav-two">                   
                <li><a href="<?php echo $this->baseUrl() ?>/admin">Mensajes</a><span class="counter">22</span></li>
                <li class="separator"></li>
                <li><a href="<?php echo $this->baseUrl() ?>/admin">Configuraci&oacute;n</a></li>  
             </ul>
</div>
