<div class="grid-1">
    <div class="title-grid"><span> >> Reservas >> Index</span></div>
    <div class="content-gird">
            <div id="calendar"></div>
            
<!--            <iframe src="https://www.google.com/calendar/embed?title=Calendario%3A%20Barrio%20Los%20Laureles&amp;height=600&amp;wkst=2&amp;hl=es&amp;bgcolor=%23339999&amp;src=389j6g8khh3a5ja0vbsv1p3ook%40group.calendar.google.com&amp;color=%232F6309&amp;ctz=America%2FSantiago" style=" border-width:0 " width="800" height="600" frameborder="0" scrolling="no"></iframe>-->
            
<!--            <iframe width="560" height="315" src="http://www.youtube.com/embed/REMgGKtdD6Q" frameborder="0" allowfullscreen></iframe>-->
            
        <div class="clear"> </div>
    </div>
</div>
    
           