<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Admin Panel | Login</title>
	<meta name="description" content="">
    <meta name="author" content="vladproduction.ru">
    <link rel="shortcut icon" href="images/favicon.ico" />
    
    
    <!-- INICIO -->
    
    <?php  $this->headLink()
                ->prependStylesheet($this->baseUrl().'/css/login.css','screen')                                  
                
    ?>               
        <?php echo $this->headLink() ?>
    
</head>

<body>
    <section id="form-margin">
            <section id="form-login">
                <?php echo $this->layout()->content ?>
            </section>
    </section>
</body>
</html>
